library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library pll;
use pll.all;

entity telecran is
    port (
        -- FPGA
        i_clk_50: in std_logic;

        -- HDMI
        io_hdmi_i2c_scl      : inout std_logic;
        io_hdmi_i2c_sda      : inout std_logic;
        o_hdmi_tx_clk        : out std_logic;
        o_hdmi_tx_d          : out std_logic_vector(23 downto 0);
        o_hdmi_tx_de         : out std_logic;
        o_hdmi_tx_hs         : out std_logic;
        i_hdmi_tx_int        : in std_logic;
        o_hdmi_tx_vs         : out std_logic;

        -- KEYs
        i_rst_n : in std_logic;
		  
		-- LEDs
		o_leds : out std_logic_vector(9 downto 0);
		o_de10_leds : out std_logic_vector(7 downto 0);

		-- Coder
		i_left_ch_a : in std_logic;
		i_left_ch_b : in std_logic;
		i_left_pb : in std_logic;
		i_right_ch_a : in std_logic;
		i_right_ch_b : in std_logic;
		i_right_pb : in std_logic
    );
end entity telecran;

architecture rtl of telecran is
	component I2C_HDMI_Config 
		port (
			iCLK : in std_logic;
			iRST_N : in std_logic;
			I2C_SCLK : out std_logic;
			I2C_SDAT : inout std_logic;
			HDMI_TX_INT  : in std_logic
		);
	 end component;
	 
	component pll 
		port (
			refclk : in std_logic;
			rst : in std_logic;
			outclk_0 : out std_logic;
			locked : out std_logic
		);
	end component;
	
	component Encodeur
		port(
        i_A : in std_logic;
        i_B : in std_logic;
        i_clk : in std_logic;

        o_Q : out natural
    );
	end component;
	
	component hdmi_controler 
	generic (
		-- Resolution
		h_res 	: positive := 720;
		v_res 	: positive := 480;

		-- Timings magic values (480p)
		h_sync	: positive := 61;
		h_fp	: positive := 58;
		h_bp	: positive := 18;

		v_sync	: positive := 5;
		v_fp	: positive := 30;
		v_bp	: positive := 9
	);
	port (
		i_clk  		: in std_logic;
    	i_rst_n 	: in std_logic;
		
    	o_hdmi_hs   : out std_logic;
    	o_hdmi_vs   : out std_logic;
    	o_hdmi_de   : out std_logic;

		o_pixel_en : out std_logic;
		o_pixel_address : out natural range 0 to (h_res * v_res - 1);
		o_x_counter : out natural range 0 to (h_res - 1);
		o_y_counter : out natural range 0 to (v_res - 1)
  	);
	 end component;

	 component dpram
	 generic
    (
        mem_size    : natural := 720 * 480;
        data_width  : natural := 8
    );
   port 
   (   
        i_clk_a        : in std_logic;
        i_clk_b        : in std_logic;

        i_data_a    : in std_logic_vector(data_width-1 downto 0);
        i_data_b    : in std_logic_vector(data_width-1 downto 0);
        i_addr_a    : in natural range 0 to mem_size-1;
        i_addr_b    : in natural range 0 to mem_size-1;
        i_we_a      : in std_logic := '1';
        i_we_b      : in std_logic := '1';
        o_q_a       : out std_logic_vector(data_width-1 downto 0);
        o_q_b       : out std_logic_vector(data_width-1 downto 0)
   );
	end component;
	 
    constant h_res : natural := 720;
    constant v_res : natural := 480;
	 constant data_width  : natural := 8;
	 constant mem_size    : natural := 720 * 480;

	signal s_clk_27 : std_logic;
	signal s_rst_n : std_logic;	-- holds reset as long as pll is not locked
	
	signal s_encodeur_counter_g : natural := 0;
	signal s_encodeur_counter_d : natural := 0;
	
	signal s_x_counter : natural := 0;
	signal s_y_counter : natural := 0;
	
	signal s_data_a    : std_logic_vector(data_width-1 downto 0);
	signal s_data_b    : std_logic_vector(data_width-1 downto 0);
	signal s_addr_a    : natural range 0 to mem_size-1;
	signal s_addr_b    : natural range 0 to mem_size-1;
	signal s_we_a      : std_logic := '1';
	signal s_we_b      : std_logic := '1';
	signal s_q_a       : std_logic_vector(data_width-1 downto 0);
	signal s_q_b       : std_logic_vector(data_width-1 downto 0);
begin
	--o_leds <= (others => '0');
	o_de10_leds <= (others => '0');
	
	-- Frequency for HDMI is 27MHz generated by this PLL
	pll0 : component pll 
		port map (
			refclk => i_clk_50,
			rst => not(i_rst_n),
			outclk_0 => s_clk_27,
			locked => s_rst_n
		);

	-- Configures the ADV7513 for 480p
	I2C_HDMI_Config0 : component I2C_HDMI_Config 
		port map (
			iCLK => i_clk_50,
			iRST_N => i_rst_n,
			I2C_SCLK => io_hdmi_i2c_scl,
			I2C_SDAT => io_hdmi_i2c_sda,
			HDMI_TX_INT => i_hdmi_tx_int
	 );
	 
	 EncodeurG : component Encodeur
		port map (
			i_clk => i_clk_50,
			i_A => i_left_ch_a,
			i_B => i_left_ch_b,
			
			o_Q => s_encodeur_counter_g
		);
		
		EncodeurD : component Encodeur
		port map (
			i_clk => i_clk_50,
			i_A => i_right_ch_a,
			i_B => i_right_ch_b,
			
			o_Q => s_encodeur_counter_d 
		);
		
	HdmiControler : component hdmi_controler
	port map (
		i_clk => s_clk_27, 
	  i_rst_n => s_rst_n,

	  o_hdmi_hs => o_hdmi_tx_hs,
	  o_hdmi_vs => o_hdmi_tx_vs,
	  o_hdmi_de => o_hdmi_tx_de,

	  o_pixel_en => open,
	  o_pixel_address => open,
	  o_x_counter => s_x_counter,
	  o_y_counter => s_y_counter
	);
	
	dp_ram : component dpram
	port map (
		i_clk_a => i_clk_50,
		i_clk_b => i_clk_50,
		
		i_data_a => s_data_a,
		i_data_b => s_data_b,
		i_addr_a => s_addr_a,
		i_addr_b => s_addr_b,
		i_we_a => s_we_a,
		i_we_b => s_we_b,
		o_q_a => s_q_a,
		o_q_b => s_q_b
	);
	
	o_hdmi_tx_clk <= s_clk_27;
	--o_hdmi_tx_d(23 downto 16) <= std_logic_vector(to_unsigned(s_x_counter, 8));
	--o_hdmi_tx_d(15 downto 8) <= std_logic_vector(to_unsigned(s_y_counter, 8));
	--o_hdmi_tx_d(7 downto 0) <= (others => '0');
	
	
	--o_leds <= "0000000001" when s_encodeur_counter_d = 1 else
	--			 "0000000011" when s_encodeur_counter_d = 2 else
	--			 "0000000111" when s_encodeur_counter_d = 3 else
	--			 "0000001111" when s_encodeur_counter_d = 4 else
	--			 "0000011111" when s_encodeur_counter_d = 5 else
	--			 "0000111111" when s_encodeur_counter_d = 6 else
	--			 "0001111111" when s_encodeur_counter_d = 7 else
	--			 "0011111111" when s_encodeur_counter_d = 8 else
	--			 "0111111111" when s_encodeur_counter_d = 9 else
	--			 "1111111111" when s_encodeur_counter_d = 10 else
	--			 (others => '0');
			
			
	process (i_clk_50) -- Ecriture d'un pixel noir sur l'écran
	begin
		s_we_b <= '1';
		s_data_b <= "11111111";
		s_addr_b <= s_encodeur_counter_d * 720 + s_encodeur_counter_g;
	end process;
	
	process (i_clk_50) -- Lecture des adresses de la ram
	begin
		s_addr_a <= s_y_counter * 720 + s_x_counter;
		
		if i_left_pb = '0' then 
			s_we_a <= '1';
			s_data_a <= "00000000";
			o_hdmi_tx_d <= (others => '0');
		else
			s_we_a <= '0';
			o_hdmi_tx_d <= s_q_a & s_q_a & s_q_a;
		end if;
	end process;
end architecture rtl;
